name: Build

on:
  push:
    branches-ignore:
      - dependabot/**
    tags:
      - '**'

jobs:
  run-ci:
    uses: Jikoo/PlanarActions/.github/workflows/ci_maven.yml@master

  release:
    name: Create Github Release
    needs: [ run-ci ]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-ci
          path: ${{ github.event.repository.name }}-ci

      - name: Parse Tag Name
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: AnvilUnlocker ${{ steps.get_version.outputs.result }}
          draft: true
          prerelease: true
          files: ./${{ github.event.repository.name }}-ci/AnvilUnlocker.jar
